/**
 * 股票列表数据
 * 用于前端本地搜索
 * 数据来源：A股主要上市公司
 */

export interface StockInfo {
  symbol: string;      // 股票代码
  name: string;        // 股票名称
  market: 'CN' | 'HK'; // 市场
  type: 'stock' | 'etf' | 'index'; // 类型
}

// A股主要股票列表（按市值排序，包含常见股票）
export const STOCK_LIST: StockInfo[] = [
  // 沪市主板 (60开头)
  { symbol: '600519', name: '贵州茅台', market: 'CN', type: 'stock' },
  { symbol: '600036', name: '招商银行', market: 'CN', type: 'stock' },
  { symbol: '601318', name: '中国平安', market: 'CN', type: 'stock' },
  { symbol: '601166', name: '兴业银行', market: 'CN', type: 'stock' },
  { symbol: '601398', name: '工商银行', market: 'CN', type: 'stock' },
  { symbol: '601288', name: '农业银行', market: 'CN', type: 'stock' },
  { symbol: '601988', name: '中国银行', market: 'CN', type: 'stock' },
  { symbol: '601939', name: '建设银行', market: 'CN', type: 'stock' },
  { symbol: '601857', name: '中国石油', market: 'CN', type: 'stock' },
  { symbol: '601888', name: '中国中免', market: 'CN', type: 'stock' },
  { symbol: '600000', name: '浦发银行', market: 'CN', type: 'stock' },
  { symbol: '600030', name: '中信证券', market: 'CN', type: 'stock' },
  { symbol: '600016', name: '民生银行', market: 'CN', type: 'stock' },
  { symbol: '600276', name: '恒瑞医药', market: 'CN', type: 'stock' },
  { symbol: '600309', name: '万华化学', market: 'CN', type: 'stock' },
  { symbol: '600346', name: '恒力石化', market: 'CN', type: 'stock' },
  { symbol: '600438', name: '通威股份', market: 'CN', type: 'stock' },
  { symbol: '600585', name: '海螺水泥', market: 'CN', type: 'stock' },
  { symbol: '600588', name: '用友网络', market: 'CN', type: 'stock' },
  { symbol: '600690', name: '海尔智家', market: 'CN', type: 'stock' },
  { symbol: '600809', name: '山西汾酒', market: 'CN', type: 'stock' },
  { symbol: '600887', name: '伊利股份', market: 'CN', type: 'stock' },
  { symbol: '600893', name: '航发动力', market: 'CN', type: 'stock' },
  { symbol: '600900', name: '长江电力', market: 'CN', type: 'stock' },
  { symbol: '600905', name: '三峡能源', market: 'CN', type: 'stock' },
  { symbol: '601012', name: '隆基绿能', market: 'CN', type: 'stock' },
  { symbol: '601138', name: '工业富联', market: 'CN', type: 'stock' },
  { symbol: '601390', name: '中国中铁', market: 'CN', type: 'stock' },
  { symbol: '601601', name: '中国太保', market: 'CN', type: 'stock' },
  { symbol: '601628', name: '中国人寿', market: 'CN', type: 'stock' },
  { symbol: '601658', name: '邮储银行', market: 'CN', type: 'stock' },
  { symbol: '601668', name: '中国建筑', market: 'CN', type: 'stock' },
  { symbol: '601688', name: '华泰证券', market: 'CN', type: 'stock' },
  { symbol: '601728', name: '中国电信', market: 'CN', type: 'stock' },
  { symbol: '601818', name: '光大银行', market: 'CN', type: 'stock' },
  { symbol: '601857', name: '中国石油', market: 'CN', type: 'stock' },
  { symbol: '601877', name: '正泰电器', market: 'CN', type: 'stock' },
  { symbol: '601888', name: '中国中免', market: 'CN', type: 'stock' },
  { symbol: '601899', name: '紫金矿业', market: 'CN', type: 'stock' },
  { symbol: '601919', name: '中远海控', market: 'CN', type: 'stock' },
  { symbol: '601985', name: '中国核电', market: 'CN', type: 'stock' },
  { symbol: '603259', name: '药明康德', market: 'CN', type: 'stock' },
  { symbol: '603288', name: '海天味业', market: 'CN', type: 'stock' },
  { symbol: '603501', name: '韦尔股份', market: 'CN', type: 'stock' },
  { symbol: '603986', name: '兆易创新', market: 'CN', type: 'stock' },

  // 深市主板 (00开头)
  { symbol: '000001', name: '平安银行', market: 'CN', type: 'stock' },
  { symbol: '000002', name: '万科A', market: 'CN', type: 'stock' },
  { symbol: '000063', name: '中兴通讯', market: 'CN', type: 'stock' },
  { symbol: '000333', name: '美的集团', market: 'CN', type: 'stock' },
  { symbol: '000338', name: '潍柴动力', market: 'CN', type: 'stock' },
  { symbol: '000425', name: '徐工机械', market: 'CN', type: 'stock' },
  { symbol: '000568', name: '泸州老窖', market: 'CN', type: 'stock' },
  { symbol: '000625', name: '长安汽车', market: 'CN', type: 'stock' },
  { symbol: '000651', name: '格力电器', market: 'CN', type: 'stock' },
  { symbol: '000703', name: '中兴通讯', market: 'CN', type: 'stock' },
  { symbol: '000708', name: '中信特钢', market: 'CN', type: 'stock' },
  { symbol: '000725', name: '京东方A', market: 'CN', type: 'stock' },
  { symbol: '000768', name: '中航西飞', market: 'CN', type: 'stock' },
  { symbol: '000776', name: '广发证券', market: 'CN', type: 'stock' },
  { symbol: '000858', name: '五粮液', market: 'CN', type: 'stock' },
  { symbol: '000876', name: '新希望', market: 'CN', type: 'stock' },
  { symbol: '000895', name: '双汇发展', market: 'CN', type: 'stock' },
  { symbol: '000938', name: '紫光股份', market: 'CN', type: 'stock' },
  { symbol: '000963', name: '华东医药', market: 'CN', type: 'stock' },
  { symbol: '000977', name: '浪潮信息', market: 'CN', type: 'stock' },
  { symbol: '001979', name: '招商蛇口', market: 'CN', type: 'stock' },

  // 创业板 (30开头)
  { symbol: '300014', name: '亿纬锂能', market: 'CN', type: 'stock' },
  { symbol: '300015', name: '爱尔眼科', market: 'CN', type: 'stock' },
  { symbol: '300033', name: '同花顺', market: 'CN', type: 'stock' },
  { symbol: '300059', name: '东方财富', market: 'CN', type: 'stock' },
  { symbol: '300124', name: '汇川技术', market: 'CN', type: 'stock' },
  { symbol: '300142', name: '沃森生物', market: 'CN', type: 'stock' },
  { symbol: '300223', name: '北京君正', market: 'CN', type: 'stock' },
  { symbol: '300274', name: '阳光电源', market: 'CN', type: 'stock' },
  { symbol: '300308', name: '中际旭创', market: 'CN', type: 'stock' },
  { symbol: '300327', name: '中颖电子', market: 'CN', type: 'stock' },
  { symbol: '300347', name: '泰格医药', market: 'CN', type: 'stock' },
  { symbol: '300408', name: '三环集团', market: 'CN', type: 'stock' },
  { symbol: '300413', name: '芒果超媒', market: 'CN', type: 'stock' },
  { symbol: '300433', name: '蓝思科技', market: 'CN', type: 'stock' },
  { symbol: '300450', name: '先导智能', market: 'CN', type: 'stock' },
  { symbol: '300454', name: '深信服', market: 'CN', type: 'stock' },
  { symbol: '300460', name: '惠伦晶体', market: 'CN', type: 'stock' },
  { symbol: '300496', name: '中科创达', market: 'CN', type: 'stock' },
  { symbol: '300498', name: '温氏股份', market: 'CN', type: 'stock' },
  { symbol: '300595', name: '欧普康视', market: 'CN', type: 'stock' },
  { symbol: '300628', name: '亿联网络', market: 'CN', type: 'stock' },
  { symbol: '300750', name: '宁德时代', market: 'CN', type: 'stock' },
  { symbol: '300760', name: '迈瑞医疗', market: 'CN', type: 'stock' },
  { symbol: '300782', name: '卓胜微', market: 'CN', type: 'stock' },
  { symbol: '300896', name: '爱美客', market: 'CN', type: 'stock' },

  // 科创板 (688开头)
  { symbol: '688001', name: '华兴源创', market: 'CN', type: 'stock' },
  { symbol: '688012', name: '中微公司', market: 'CN', type: 'stock' },
  { symbol: '688041', name: '海光信息', market: 'CN', type: 'stock' },
  { symbol: '688111', name: '金山办公', market: 'CN', type: 'stock' },
  { symbol: '688126', name: '沪硅产业', market: 'CN', type: 'stock' },
  { symbol: '688169', name: '石头科技', market: 'CN', type: 'stock' },
  { symbol: '688180', name: '君实生物', market: 'CN', type: 'stock' },
  { symbol: '688187', name: '时代电气', market: 'CN', type: 'stock' },
  { symbol: '688223', name: '晶科能源', market: 'CN', type: 'stock' },
  { symbol: '688256', name: '寒武纪', market: 'CN', type: 'stock' },
  { symbol: '688303', name: '大全能源', market: 'CN', type: 'stock' },
  { symbol: '688369', name: '致远互联', market: 'CN', type: 'stock' },
  { symbol: '688396', name: '华润微', market: 'CN', type: 'stock' },
  { symbol: '688567', name: '孚能科技', market: 'CN', type: 'stock' },
  { symbol: '688599', name: '天合光能', market: 'CN', type: 'stock' },
  { symbol: '688981', name: '中芯国际', market: 'CN', type: 'stock' },

  // 港股
  { symbol: '00700', name: '腾讯控股', market: 'HK', type: 'stock' },
  { symbol: '09988', name: '阿里巴巴', market: 'HK', type: 'stock' },
  { symbol: '09999', name: '网易', market: 'HK', type: 'stock' },
  { symbol: '09618', name: '京东集团', market: 'HK', type: 'stock' },
  { symbol: '03690', name: '美团', market: 'HK', type: 'stock' },
  { symbol: '01024', name: '快手', market: 'HK', type: 'stock' },
  { symbol: '09961', name: '比亚迪股份', market: 'HK', type: 'stock' },
  { symbol: '02318', name: '中国平安', market: 'HK', type: 'stock' },
  { symbol: '00941', name: '中国移动', market: 'HK', type: 'stock' },
  { symbol: '03988', name: '中国银行', market: 'HK', type: 'stock' },
  { symbol: '01398', name: '工商银行', market: 'HK', type: 'stock' },
  { symbol: '01288', name: '农业银行', market: 'HK', type: 'stock' },
  { symbol: '00939', name: '建设银行', market: 'HK', type: 'stock' },
  { symbol: '02628', name: '中国人寿', market: 'HK', type: 'stock' },
  { symbol: '00883', name: '中国海洋石油', market: 'HK', type: 'stock' },
  { symbol: '00386', name: '中国石油化工', market: 'HK', type: 'stock' },
  { symbol: '01810', name: '小米集团', market: 'HK', type: 'stock' },
  { symbol: '02015', name: '理想汽车', market: 'HK', type: 'stock' },
  { symbol: '09868', name: '小鹏汽车', market: 'HK', type: 'stock' },
  { symbol: '09626', name: '哔哩哔哩', market: 'HK', type: 'stock' },
  
  // 更多A股热门股票
  { symbol: '600009', name: '上海机场', market: 'CN', type: 'stock' },
  { symbol: '600010', name: '包钢股份', market: 'CN', type: 'stock' },
  { symbol: '600011', name: '华能国际', market: 'CN', type: 'stock' },
  { symbol: '600015', name: '华夏银行', market: 'CN', type: 'stock' },
  { symbol: '600019', name: '宝钢股份', market: 'CN', type: 'stock' },
  { symbol: '600028', name: '中国石化', market: 'CN', type: 'stock' },
  { symbol: '600029', name: '南方航空', market: 'CN', type: 'stock' },
  { symbol: '600031', name: '三一重工', market: 'CN', type: 'stock' },
  { symbol: '600033', name: '福建高速', market: 'CN', type: 'stock' },
  { symbol: '600035', name: '楚天高速', market: 'CN', type: 'stock' },
  { symbol: '600037', name: '歌华有线', market: 'CN', type: 'stock' },
  { symbol: '600048', name: '保利发展', market: 'CN', type: 'stock' },
  { symbol: '600050', name: '中国联通', market: 'CN', type: 'stock' },
  { symbol: '600056', name: '中国医药', market: 'CN', type: 'stock' },
  { symbol: '600058', name: '五矿发展', market: 'CN', type: 'stock' },
  { symbol: '600059', name: '古越龙山', market: 'CN', type: 'stock' },
  { symbol: '600060', name: '海信视像', market: 'CN', type: 'stock' },
  { symbol: '600061', name: '国投资本', market: 'CN', type: 'stock' },
  { symbol: '600062', name: '华润双鹤', market: 'CN', type: 'stock' },
  { symbol: '600063', name: '皖维高新', market: 'CN', type: 'stock' },
  { symbol: '600066', name: '宇通客车', market: 'CN', type: 'stock' },
  { symbol: '600067', name: '冠城大通', market: 'CN', type: 'stock' },
  { symbol: '600068', name: '葛洲坝', market: 'CN', type: 'stock' },
  { symbol: '600069', name: '银鸽投资', market: 'CN', type: 'stock' },
  { symbol: '600070', name: '浙江富润', market: 'CN', type: 'stock' },
  { symbol: '600071', name: '凤凰光学', market: 'CN', type: 'stock' },
  { symbol: '600072', name: '中船科技', market: 'CN', type: 'stock' },
  { symbol: '600073', name: '上海梅林', market: 'CN', type: 'stock' },
  { symbol: '600074', name: '退市保千', market: 'CN', type: 'stock' },
  { symbol: '600075', name: '新疆天业', market: 'CN', type: 'stock' },
  { symbol: '600076', name: '康欣新材', market: 'CN', type: 'stock' },
  { symbol: '600077', name: '宋都股份', market: 'CN', type: 'stock' },
  { symbol: '600078', name: '澄星股份', market: 'CN', type: 'stock' },
  { symbol: '600079', name: '人福医药', market: 'CN', type: 'stock' },
  { symbol: '600080', name: '金花股份', market: 'CN', type: 'stock' },
  { symbol: '600081', name: '东风科技', market: 'CN', type: 'stock' },
  { symbol: '600082', name: '海泰发展', market: 'CN', type: 'stock' },
  { symbol: '600083', name: '博信股份', market: 'CN', type: 'stock' },
  { symbol: '600084', name: '中葡股份', market: 'CN', type: 'stock' },
  { symbol: '600085', name: '同仁堂', market: 'CN', type: 'stock' },
  { symbol: '600086', name: '东方金钰', market: 'CN', type: 'stock' },
  { symbol: '600088', name: '中视传媒', market: 'CN', type: 'stock' },
  { symbol: '600089', name: '特变电工', market: 'CN', type: 'stock' },
  { symbol: '600090', name: '啤酒花', market: 'CN', type: 'stock' },
  { symbol: '600091', name: '明星电力', market: 'CN', type: 'stock' },
  { symbol: '600092', name: '爱柯迪', market: 'CN', type: 'stock' },
  { symbol: '600093', name: '易见股份', market: 'CN', type: 'stock' },
  { symbol: '600094', name: '大名城', market: 'CN', type: 'stock' },
  { symbol: '600095', name: '哈高科', market: 'CN', type: 'stock' },
  { symbol: '600096', name: '云天化', market: 'CN', type: 'stock' },
  { symbol: '600097', name: '开创国际', market: 'CN', type: 'stock' },
  { symbol: '600098', name: '广州发展', market: 'CN', type: 'stock' },
  { symbol: '600099', name: '林海股份', market: 'CN', type: 'stock' },
  { symbol: '600100', name: '同方股份', market: 'CN', type: 'stock' },
  { symbol: '600101', name: '明星电力', market: 'CN', type: 'stock' },
  { symbol: '600102', name: '莱钢股份', market: 'CN', type: 'stock' },
  { symbol: '600103', name: '青山纸业', market: 'CN', type: 'stock' },
  { symbol: '600104', name: '上汽集团', market: 'CN', type: 'stock' },
  { symbol: '600105', name: '永鼎股份', market: 'CN', type: 'stock' },
  { symbol: '600106', name: '重庆路桥', market: 'CN', type: 'stock' },
  { symbol: '600107', name: '美尔雅', market: 'CN', type: 'stock' },
  { symbol: '600108', name: '亚盛集团', market: 'CN', type: 'stock' },
  { symbol: '600109', name: '国金证券', market: 'CN', type: 'stock' },
  { symbol: '600110', name: '诺德股份', market: 'CN', type: 'stock' },
  { symbol: '600111', name: '北方稀土', market: 'CN', type: 'stock' },
  { symbol: '600112', name: '天成控股', market: 'CN', type: 'stock' },
  { symbol: '600113', name: '浙江东日', market: 'CN', type: 'stock' },
  { symbol: '600114', name: '东睦股份', market: 'CN', type: 'stock' },
  { symbol: '600115', name: '中国东航', market: 'CN', type: 'stock' },
  { symbol: '600116', name: '三峡水利', market: 'CN', type: 'stock' },
  { symbol: '600117', name: '西宁特钢', market: 'CN', type: 'stock' },
  { symbol: '600118', name: '中国卫星', market: 'CN', type: 'stock' },
  { symbol: '600119', name: '长江投资', market: 'CN', type: 'stock' },
  { symbol: '600120', name: '浙江东方', market: 'CN', type: 'stock' },
  { symbol: '600121', name: '郑州煤电', market: 'CN', type: 'stock' },
  { symbol: '600122', name: '宏图高科', market: 'CN', type: 'stock' },
  { symbol: '600123', name: '兰花科创', market: 'CN', type: 'stock' },
  { symbol: '600125', name: '铁龙物流', market: 'CN', type: 'stock' },
  { symbol: '600126', name: '杭钢股份', market: 'CN', type: 'stock' },
  { symbol: '600127', name: '金健米业', market: 'CN', type: 'stock' },
  { symbol: '600128', name: '弘业股份', market: 'CN', type: 'stock' },
  { symbol: '600129', name: '太极集团', market: 'CN', type: 'stock' },
  { symbol: '600130', name: '波导股份', market: 'CN', type: 'stock' },
  { symbol: '600131', name: '岷江水电', market: 'CN', type: 'stock' },
  { symbol: '600132', name: '重庆啤酒', market: 'CN', type: 'stock' },
  { symbol: '600133', name: '东湖高新', market: 'CN', type: 'stock' },
  { symbol: '600134', name: '彩虹股份', market: 'CN', type: 'stock' },
  { symbol: '600135', name: '乐凯胶片', market: 'CN', type: 'stock' },
  { symbol: '600136', name: '当代文体', market: 'CN', type: 'stock' },
  { symbol: '600137', name: '浪莎股份', market: 'CN', type: 'stock' },
  { symbol: '600138', name: '中青旅', market: 'CN', type: 'stock' },
  { symbol: '600139', name: '西部资源', market: 'CN', type: 'stock' },
  { symbol: '600140', name: '东吴证券', market: 'CN', type: 'stock' },
  { symbol: '600141', name: '兴发集团', market: 'CN', type: 'stock' },
  { symbol: '600142', name: '沱牌舍得', market: 'CN', type: 'stock' },
  { symbol: '600143', name: '金发科技', market: 'CN', type: 'stock' },
  { symbol: '600144', name: '瑞贝卡', market: 'CN', type: 'stock' },
  { symbol: '600145', name: '中核钛白', market: 'CN', type: 'stock' },
  { symbol: '600146', name: '商赢环球', market: 'CN', type: 'stock' },
  { symbol: '600147', name: '长春一东', market: 'CN', type: 'stock' },
  { symbol: '600148', name: '长春一东', market: 'CN', type: 'stock' },
  { symbol: '600149', name: '廊房发展', market: 'CN', type: 'stock' },
  { symbol: '600150', name: '中国船舶', market: 'CN', type: 'stock' },
  { symbol: '600151', name: '航天机电', market: 'CN', type: 'stock' },
  { symbol: '600152', name: '维科技术', market: 'CN', type: 'stock' },
  { symbol: '600153', name: '建发股份', market: 'CN', type: 'stock' },
  { symbol: '600154', name: '光电股份', market: 'CN', type: 'stock' },
  { symbol: '600155', name: '华创阳安', market: 'CN', type: 'stock' },
  { symbol: '600156', name: '华升股份', market: 'CN', type: 'stock' },
  { symbol: '600157', name: '永泰能源', market: 'CN', type: 'stock' },
  { symbol: '600158', name: '中体产业', market: 'CN', type: 'stock' },
  { symbol: '600159', name: '大龙地产', market: 'CN', type: 'stock' },
  { symbol: '600160', name: '巨化股份', market: 'CN', type: 'stock' },
  { symbol: '600161', name: '天坛生物', market: 'CN', type: 'stock' },
  { symbol: '600162', name: '香江控股', market: 'CN', type: 'stock' },
  { symbol: '600163', name: '中闽能源', market: 'CN', type: 'stock' },
  { symbol: '600164', name: '中捷资源', market: 'CN', type: 'stock' },
  { symbol: '600165', name: '新日恒力', market: 'CN', type: 'stock' },
  { symbol: '600166', name: '福田汽车', market: 'CN', type: 'stock' },
  { symbol: '600167', name: '联美控股', market: 'CN', type: 'stock' },
  { symbol: '600168', name: '武汉控股', market: 'CN', type: 'stock' },
  { symbol: '600169', name: '太原重工', market: 'CN', type: 'stock' },
  { symbol: '600170', name: '上海建工', market: 'CN', type: 'stock' },
  { symbol: '600171', name: '上海贝岭', market: 'CN', type: 'stock' },
  { symbol: '600172', name: '黄河旋风', market: 'CN', type: 'stock' },
  { symbol: '600173', name: '卧龙地产', market: 'CN', type: 'stock' },
  { symbol: '600175', name: '美都能源', market: 'CN', type: 'stock' },
  { symbol: '600176', name: '中国巨石', market: 'CN', type: 'stock' },
  { symbol: '600177', name: '雅戈尔', market: 'CN', type: 'stock' },
  { symbol: '600178', name: '东安动力', market: 'CN', type: 'stock' },
  { symbol: '600179', name: '安通控股', market: 'CN', type: 'stock' },
  { symbol: '600180', name: '瑞茂通', market: 'CN', type: 'stock' },
  { symbol: '600181', name: '佳都科技', market: 'CN', type: 'stock' },
  { symbol: '600182', name: 'S佳通', market: 'CN', type: 'stock' },
  { symbol: '600183', name: '生益科技', market: 'CN', type: 'stock' },
  { symbol: '600184', name: '光电股份', market: 'CN', type: 'stock' },
  { symbol: '600185', name: '格力地产', market: 'CN', type: 'stock' },
  { symbol: '600186', name: '莲花健康', market: 'CN', type: 'stock' },
  { symbol: '600187', name: '国中水务', market: 'CN', type: 'stock' },
  { symbol: '600188', name: '兖矿能源', market: 'CN', type: 'stock' },
  { symbol: '600189', name: '泉阳泉', market: 'CN', type: 'stock' },
  { symbol: '600190', name: '锦州港', market: 'CN', type: 'stock' },
  { symbol: '600191', name: '华资实业', market: 'CN', type: 'stock' },
  { symbol: '600192', name: '长城电工', market: 'CN', type: 'stock' },
  { symbol: '600193', name: '创兴资源', market: 'CN', type: 'stock' },
  { symbol: '600194', name: '胜利股份', market: 'CN', type: 'stock' },
  { symbol: '600195', name: '中牧股份', market: 'CN', type: 'stock' },
  { symbol: '600196', name: '复星医药', market: 'CN', type: 'stock' },
  { symbol: '600197', name: '伊力特', market: 'CN', type: 'stock' },
  { symbol: '600198', name: '大唐电信', market: 'CN', type: 'stock' },
  { symbol: '600199', name: '金种子酒', market: 'CN', type: 'stock' },
  { symbol: '600200', name: '江苏吴中', market: 'CN', type: 'stock' },
  { symbol: '600201', name: '生物股份', market: 'CN', type: 'stock' },
  { symbol: '600202', name: '哈空调', market: 'CN', type: 'stock' },
  { symbol: '600203', name: '福日电子', market: 'CN', type: 'stock' },
  { symbol: '600206', name: '有研新材', market: 'CN', type: 'stock' },
  { symbol: '600207', name: '安彩高科', market: 'CN', type: 'stock' },
  { symbol: '600208', name: '新湖中宝', market: 'CN', type: 'stock' },
  { symbol: '600209', name: '罗顿发展', market: 'CN', type: 'stock' },
  { symbol: '600210', name: '紫江企业', market: 'CN', type: 'stock' },
  { symbol: '600211', name: '西藏药业', market: 'CN', type: 'stock' },
  { symbol: '600212', name: '江泉实业', market: 'CN', type: 'stock' },
  { symbol: '600213', name: '亚星客车', market: 'CN', type: 'stock' },
  { symbol: '600215', name: '长春经开', market: 'CN', type: 'stock' },
  { symbol: '600216', name: '浙江医药', market: 'CN', type: 'stock' },
  { symbol: '600217', name: '中再资环', market: 'CN', type: 'stock' },
  { symbol: '600218', name: '全柴动力', market: 'CN', type: 'stock' },
  { symbol: '600219', name: '南山铝业', market: 'CN', type: 'stock' },
  { symbol: '600220', name: '江苏阳光', market: 'CN', type: 'stock' },
  { symbol: '600221', name: '海南航空', market: 'CN', type: 'stock' },
  { symbol: '600222', name: '太龙药业', market: 'CN', type: 'stock' },
  { symbol: '600223', name: '鲁商发展', market: 'CN', type: 'stock' },
  { symbol: '600225', name: '卓朗科技', market: 'CN', type: 'stock' },
  { symbol: '600226', name: '升华拜克', market: 'CN', type: 'stock' },
  { symbol: '600227', name: '赤天化', market: 'CN', type: 'stock' },
  { symbol: '600228', name: '昌九生化', market: 'CN', type: 'stock' },
  { symbol: '600229', name: '城市传媒', market: 'CN', type: 'stock' },
  { symbol: '600230', name: '沧州大化', market: 'CN', type: 'stock' },
  { symbol: '600231', name: '凌钢股份', market: 'CN', type: 'stock' },
  { symbol: '600232', name: '金鹰股份', market: 'CN', type: 'stock' },
  { symbol: '600233', name: '圆通速递', market: 'CN', type: 'stock' },
  { symbol: '600234', name: 'ST天鹅', market: 'CN', type: 'stock' },
  { symbol: '600235', name: '民丰特纸', market: 'CN', type: 'stock' },
  { symbol: '600236', name: '桂冠电力', market: 'CN', type: 'stock' },
  { symbol: '600237', name: '铜峰电子', market: 'CN', type: 'stock' },
  { symbol: '600238', name: '海南椰岛', market: 'CN', type: 'stock' },
  { symbol: '600239', name: '云南城投', market: 'CN', type: 'stock' },
  { symbol: '600240', name: '华业资本', market: 'CN', type: 'stock' },
  { symbol: '600241', name: '时代万恒', market: 'CN', type: 'stock' },
  { symbol: '600242', name: '中昌数据', market: 'CN', type: 'stock' },
  { symbol: '600243', name: '青海华鼎', market: 'CN', type: 'stock' },
  { symbol: '600244', name: '明星电缆', market: 'CN', type: 'stock' },
  { symbol: '600245', name: '*ST国创', market: 'CN', type: 'stock' },
  { symbol: '600246', name: '万通地产', market: 'CN', type: 'stock' },
  { symbol: '600247', name: 'ST成城', market: 'CN', type: 'stock' },
  { symbol: '600248', name: '陕西建工', market: 'CN', type: 'stock' },
  { symbol: '600249', name: '两面针', market: 'CN', type: 'stock' },
  { symbol: '600250', name: '南京商旅', market: 'CN', type: 'stock' },
  { symbol: '600251', name: '冠农股份', market: 'CN', type: 'stock' },
  { symbol: '600252', name: '中恒集团', market: 'CN', type: 'stock' },
  { symbol: '600253', name: '天方药业', market: 'CN', type: 'stock' },
  { symbol: '600255', name: '鑫科材料', market: 'CN', type: 'stock' },
  { symbol: '600256', name: '广汇能源', market: 'CN', type: 'stock' },
  { symbol: '600257', name: '大湖股份', market: 'CN', type: 'stock' },
  { symbol: '600258', name: '首旅酒店', market: 'CN', type: 'stock' },
  { symbol: '600259', name: '广晟有色', market: 'CN', type: 'stock' },
  { symbol: '600260', name: '凯乐科技', market: 'CN', type: 'stock' },
  { symbol: '600261', name: '阳光照明', market: 'CN', type: 'stock' },
  { symbol: '600262', name: '北方股份', market: 'CN', type: 'stock' },
  { symbol: '600263', name: '路桥建设', market: 'CN', type: 'stock' },
  { symbol: '600264', name: '世纪瑞尔', market: 'CN', type: 'stock' },
  { symbol: '600265', name: 'ST景谷', market: 'CN', type: 'stock' },
  { symbol: '600266', name: '城建发展', market: 'CN', type: 'stock' },
  { symbol: '600267', name: '海正药业', market: 'CN', type: 'stock' },
  { symbol: '600268', name: '国电南自', market: 'CN', type: 'stock' },
  { symbol: '600269', name: '赣粤高速', market: 'CN', type: 'stock' },
  { symbol: '600270', name: '外运发展', market: 'CN', type: 'stock' },
  { symbol: '600271', name: '航天信息', market: 'CN', type: 'stock' },
  { symbol: '600272', name: '开开实业', market: 'CN', type: 'stock' },
  { symbol: '600273', name: '嘉化能源', market: 'CN', type: 'stock' },
  { symbol: '600275', name: '武昌鱼', market: 'CN', type: 'stock' },
  { symbol: '600277', name: '亿利洁能', market: 'CN', type: 'stock' },
  { symbol: '600278', name: '东方创业', market: 'CN', type: 'stock' },
  { symbol: '600279', name: '重庆港九', market: 'CN', type: 'stock' },
  { symbol: '600280', name: '中央商场', market: 'CN', type: 'stock' },
  { symbol: '600281', name: '太化股份', market: 'CN', type: 'stock' },
  { symbol: '600282', name: '南钢股份', market: 'CN', type: 'stock' },
  { symbol: '600283', name: '钱江水利', market: 'CN', type: 'stock' },
  { symbol: '600284', name: '浦东建设', market: 'CN', type: 'stock' },
  { symbol: '600285', name: '羚锐制药', market: 'CN', type: 'stock' },
  { symbol: '600286', name: '国光瓷业', market: 'CN', type: 'stock' },
  { symbol: '600287', name: '江苏舜天', market: 'CN', type: 'stock' },
  { symbol: '600288', name: '大恒科技', market: 'CN', type: 'stock' },
  { symbol: '600289', name: '亿阳信通', market: 'CN', type: 'stock' },
  { symbol: '600290', name: '华仪电气', market: 'CN', type: 'stock' },
  { symbol: '600291', name: '西水股份', market: 'CN', type: 'stock' },
  { symbol: '600292', name: '远达环保', market: 'CN', type: 'stock' },
  { symbol: '600293', name: '三峡新材', market: 'CN', type: 'stock' },
  { symbol: '600295', name: '鄂尔多斯', market: 'CN', type: 'stock' },
  { symbol: '600297', name: '广汇汽车', market: 'CN', type: 'stock' },
  { symbol: '600298', name: '安琪酵母', market: 'CN', type: 'stock' },
  { symbol: '600299', name: '安迪苏', market: 'CN', type: 'stock' },
  { symbol: '600300', name: '维维股份', market: 'CN', type: 'stock' },
  { symbol: '600301', name: 'ST南化', market: 'CN', type: 'stock' },
  { symbol: '600302', name: '标准股份', market: 'CN', type: 'stock' },
  { symbol: '600303', name: '曙光股份', market: 'CN', type: 'stock' },
  { symbol: '600305', name: '恒顺醋业', market: 'CN', type: 'stock' },
  { symbol: '600306', name: 'ST商城', market: 'CN', type: 'stock' },
  { symbol: '600307', name: '酒钢宏兴', market: 'CN', type: 'stock' },
  { symbol: '600308', name: '华泰股份', market: 'CN', type: 'stock' },
  { symbol: '600310', name: '桂东电力', market: 'CN', type: 'stock' },
  { symbol: '600311', name: '荣华实业', market: 'CN', type: 'stock' },
  { symbol: '600312', name: '平高电气', market: 'CN', type: 'stock' },
  { symbol: '600313', name: '农发种业', market: 'CN', type: 'stock' },
  { symbol: '600315', name: '上海家化', market: 'CN', type: 'stock' },
  { symbol: '600316', name: '洪都航空', market: 'CN', type: 'stock' },
  { symbol: '600317', name: '营口港', market: 'CN', type: 'stock' },
  { symbol: '600318', name: '新力金融', market: 'CN', type: 'stock' },
  { symbol: '600319', name: '亚星化学', market: 'CN', type: 'stock' },
  { symbol: '600320', name: '振华重工', market: 'CN', type: 'stock' },
  { symbol: '600321', name: '国栋建设', market: 'CN', type: 'stock' },
  { symbol: '600322', name: '天房发展', market: 'CN', type: 'stock' },
  { symbol: '600323', name: '瀚蓝环境', market: 'CN', type: 'stock' },
  { symbol: '600325', name: '华发股份', market: 'CN', type: 'stock' },
  { symbol: '600326', name: '西藏天路', market: 'CN', type: 'stock' },
  { symbol: '600327', name: '大东方', market: 'CN', type: 'stock' },
  { symbol: '600328', name: '兰太实业', market: 'CN', type: 'stock' },
  { symbol: '600329', name: '中新药业', market: 'CN', type: 'stock' },
  { symbol: '600330', name: '天通股份', market: 'CN', type: 'stock' },
  { symbol: '600331', name: '宏达股份', market: 'CN', type: 'stock' },
  { symbol: '600332', name: '白云山', market: 'CN', type: 'stock' },
  { symbol: '600333', name: '长春燃气', market: 'CN', type: 'stock' },
  { symbol: '600335', name: '国机汽车', market: 'CN', type: 'stock' },
  { symbol: '600336', name: '澳柯玛', market: 'CN', type: 'stock' },
  { symbol: '600337', name: '美克家居', market: 'CN', type: 'stock' },
  { symbol: '600338', name: 'ST珠峰', market: 'CN', type: 'stock' },
  { symbol: '600339', name: '中油工程', market: 'CN', type: 'stock' },
  { symbol: '600340', name: '华夏幸福', market: 'CN', type: 'stock' },
  { symbol: '600343', name: '航天动力', market: 'CN', type: 'stock' },
  { symbol: '600345', name: '长江通信', market: 'CN', type: 'stock' },
  { symbol: '600346', name: '恒力石化', market: 'CN', type: 'stock' },
  { symbol: '600348', name: '华阳股份', market: 'CN', type: 'stock' },
  { symbol: '600349', name: '新能源', market: 'CN', type: 'stock' },
  { symbol: '600350', name: '山东高速', market: 'CN', type: 'stock' },
  { symbol: '600351', name: '亚宝药业', market: 'CN', type: 'stock' },
  { symbol: '600352', name: '浙江龙盛', market: 'CN', type: 'stock' },
  { symbol: '600353', name: '旭光电子', market: 'CN', type: 'stock' },
  { symbol: '600354', name: '敦煌种业', market: 'CN', type: 'stock' },
  { symbol: '600355', name: '精伦电子', market: 'CN', type: 'stock' },
  { symbol: '600356', name: '恒丰纸业', market: 'CN', type: 'stock' },
  { symbol: '600357', name: '国联股份', market: 'CN', type: 'stock' },
  { symbol: '600358', name: '国旅联合', market: 'CN', type: 'stock' },
  { symbol: '600359', name: '新农开发', market: 'CN', type: 'stock' },
  { symbol: '600360', name: '华微电子', market: 'CN', type: 'stock' },
  { symbol: '600361', name: '创新资源', market: 'CN', type: 'stock' },
  { symbol: '600362', name: '江西铜业', market: 'CN', type: 'stock' },
  { symbol: '600363', name: '联创光电', market: 'CN', type: 'stock' },
  { symbol: '600364', name: '宁波韵升', market: 'CN', type: 'stock' },
  { symbol: '600365', name: '通葡股份', market: 'CN', type: 'stock' },
  { symbol: '600366', name: '宁波韵升', market: 'CN', type: 'stock' },
  { symbol: '600367', name: '红星发展', market: 'CN', type: 'stock' },
  { symbol: '600368', name: '五洲交通', market: 'CN', type: 'stock' },
  { symbol: '600369', name: '西南证券', market: 'CN', type: 'stock' },
  { symbol: '600370', name: '三房巷', market: 'CN', type: 'stock' },
  { symbol: '600371', name: '万向德农', market: 'CN', type: 'stock' },
  { symbol: '600372', name: '中航电子', market: 'CN', type: 'stock' },
  { symbol: '600373', name: '中文传媒', market: 'CN', type: 'stock' },
  { symbol: '600376', name: '首开股份', market: 'CN', type: 'stock' },
  { symbol: '600377', name: '宁沪高速', market: 'CN', type: 'stock' },
  { symbol: '600378', name: '昊华科技', market: 'CN', type: 'stock' },
  { symbol: '600379', name: '宝光股份', market: 'CN', type: 'stock' },
  { symbol: '600380', name: '健康元', market: 'CN', type: 'stock' },
  { symbol: '600381', name: '青海春天', market: 'CN', type: 'stock' },
  { symbol: '600382', name: '粤电力A', market: 'CN', type: 'stock' },
  { symbol: '600383', name: '金地集团', market: 'CN', type: 'stock' },
  { symbol: '600385', name: '山东金泰', market: 'CN', type: 'stock' },
  { symbol: '600386', name: '北巴传媒', market: 'CN', type: 'stock' },
  { symbol: '600387', name: '海越股份', market: 'CN', type: 'stock' },
  { symbol: '600388', name: '龙净环保', market: 'CN', type: 'stock' },
  { symbol: '600389', name: '江山股份', market: 'CN', type: 'stock' },
  { symbol: '600390', name: '五矿资本', market: 'CN', type: 'stock' },
  { symbol: '600391', name: '成发科技', market: 'CN', type: 'stock' },
  { symbol: '600392', name: '盛和资源', market: 'CN', type: 'stock' },
  { symbol: '600393', name: '粤泰股份', market: 'CN', type: 'stock' },
  { symbol: '600395', name: '盘江股份', market: 'CN', type: 'stock' },
  { symbol: '600396', name: '金山股份', market: 'CN', type: 'stock' },
  { symbol: '600397', name: '安源煤业', market: 'CN', type: 'stock' },
  { symbol: '600398', name: '海澜之家', market: 'CN', type: 'stock' },
  { symbol: '600399', name: '抚顺特钢', market: 'CN', type: 'stock' },
];

/**
 * 本地搜索股票
 * @param keyword 搜索关键词（股票代码或名称）
 * @param limit 返回结果数量限制
 * @returns 匹配的股票列表
 */
export function searchStocks(keyword: string, limit: number = 10): StockInfo[] {
  if (!keyword || keyword.trim() === '') {
    return [];
  }

  const searchTerm = keyword.trim().toLowerCase();
  
  return STOCK_LIST
    .filter(stock => {
      // 匹配股票代码
      if (stock.symbol.toLowerCase().includes(searchTerm)) {
        return true;
      }
      // 匹配股票名称
      if (stock.name.toLowerCase().includes(searchTerm)) {
        return true;
      }
      return false;
    })
    .slice(0, limit);
}

/**
 * 根据股票代码获取股票信息
 * @param symbol 股票代码
 * @returns 股票信息或 undefined
 */
export function getStockInfo(symbol: string): StockInfo | undefined {
  return STOCK_LIST.find(stock => stock.symbol === symbol);
}

/**
 * 根据股票名称获取股票信息
 * @param name 股票名称
 * @returns 股票信息或 undefined
 */
export function getStockInfoByName(name: string): StockInfo | undefined {
  return STOCK_LIST.find(stock => stock.name === name);
}

export default {
  STOCK_LIST,
  searchStocks,
  getStockInfo,
  getStockInfoByName,
};
