supabase functions delete admin-operations --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete cancel-trade --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete create-trade --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete f10-mock --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete galaxy-news --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete galaxy-news-feed --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete ipo-subscribe --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete limit-up-submit --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete match-trade-order --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete mock-quotes --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete nexus-sync --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete order-validator --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete quotes-mock --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete trade-audit --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete trade-cancel --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete trade-matcher --project-ref rfnrosyfeivcbkimjlwo
supabase functions delete trade-matcher-v2 --project-ref rfnrosyfeivcbkimjlwo
